added template diff tracking and history
oboehmer/dnac-template-as-code pull request #2
Opened 2022-08-25 20:48 UTC by imanassypov

Added functionality:
- per-template file, add comment header with last diff
- per-template file, summary page - last 'n' commit messages history

Notes:
- recognize comment char for J2 vs Velocity
- truncate summary section to match max supported length in dnac of 1024
- variable defined DNAC_URL
- added runner build stage

2022-10-05 13:53 UTC, oboehmer requested changes
sorry for the delay, started with the review and forgot about it ;-)  a few comments and requests..

2022-10-05 13:53 UTC, oboehmer commented on .gitlab-ci.yml
> +    - macos
what do you use these tags for?

2022-10-05 13:53 UTC, oboehmer commented on deployment/Management-Access.yaml
> +  wlc01:
I would rather keep those devices in the repository, can you please revert the changes? Maybe you can apply them in your fork?

2022-10-05 13:53 UTC, oboehmer commented on scripts/DNACTemplate.py
> +            repo = Git(repo_path)
maybe do this in `__init__` so you avoid doing this multiple times?

2022-10-05 13:53 UTC, oboehmer commented on scripts/DNACTemplate.py
> +                                                                           filename))
do we want to fail the script execution if we can't do the comments/updates?

2022-10-05 13:53 UTC, oboehmer commented on scripts/DNACTemplate.py
> +                                   re.sub('__PROJECT__', self.template_project, template_content)
maybe better
```suggestion
                template_content = '{}{}'.format(template_diff,
                                   re.sub('__PROJECT__', self.template_project, template_content))
```

2022-10-05 13:53 UTC, oboehmer commented on scripts/DNACTemplate.py
> +            comments = (comments[:self.COMMENTS_MAX_CHARS]) if len(comments) > self.COMMENTS_MAX_CHARS else comments
should be enough? 
```suggestion
            comments = comments[:self.COMMENTS_MAX_CHARS]
```

2022-10-05 13:53 UTC, oboehmer commented on scripts/DNACTemplate.py
> +    COMMENTS_MAX_CHARS = 1024
should we make this configurable (i.e. fetch it from config file?)

2022-10-12 18:41 UTC, imanassypov commented
Oliver - thank you for great feedback, made changes as requested

2022-10-12 19:15 UTC, oboehmer approved these changes
Thanks for the contribution!

2022-10-12 19:16 UTC, merged